package io.phoenix;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import java.util.Date;


public class JpaPersistenceContextDemo {


    public static void main(String[] args)
    {





        Employee emp = new Employee();
        //emp.setId(1); Id is auto generated by JPA
        emp.setName("New Employee");
        emp.setSsn("586");
        emp.setDate(new Date());
        emp.setType(EmployeeType.FULL_TIME);
        System.out.println("*********Created Employee Instance");



        EntityManagerFactory entityManagerFactory= Persistence.createEntityManagerFactory("myApp");

        EntityManager entityManager = entityManagerFactory.createEntityManager();  //is an object/service which JPA provides which manages the entities
        EntityTransaction entityTransaction =entityManager.getTransaction();
        entityTransaction.begin();
        System.out.println("*****Starting Transactiom");

        entityManager.persist(emp);    // here hibernate caches the emp data
        System.out.println("***********After Persist Method called");
        Employee empFound = entityManager.find(Employee.class, 1);    // the employee details is checked insdie the cached data and retrieved
        System.out.println(empFound);
        entityTransaction.commit();       // only here the cached data is actually persisted to the database

        System.out.println("********8After Transaction closed");



        entityManager.close();
        entityManagerFactory.close();

    }
}
